apiVersion: v1
kind: Namespace
metadata:
  name: nash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      labels:
        app: demo
    spec:
      initContainers:
        - name: init-networking
          image: nash/init
          imagePullPolicy: Never
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
      - name: proxy
        image: nash/proxy
        imagePullPolicy:  Never
        ports:
          - containerPort: 8000
      - image: springguides/demo
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        name: demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: demo-svc
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
    - http:
        paths:
          - path: /villager
            backend:
              serviceName: demo-svc
              servicePort: 80